### ISSUE TITLE
Schema.JSON has degeneracy in use of "name" and "description"

### ISSUE THREAD

**Issue by DrKentB** [gwosc-tutorial/gwosc-catalog#13]
In the JSON schema file the use of "name" appears at 4(?) different levels and the use of "description" appears at 2(?) different levels. At the top level the meaning of these is very vague, but IAS has used it to mean the Catalog Name and the description (more like documentation in their case) of the catalog. It would be insightful to have the "name" changed to what is being represented by name at each level and similarly for the "description. For example:

1. name -> catalog_name & description -> catalogdescription
2. name -> event_name & description -> eventdescription
3. name -> pe_set_name 
4. name -> parameter_name

A few notes based on looking at the IAS usage of this schema: IAS did not provide the event:description in their JSON example. Is it the intent that fields in the dictionary are optional? I would suggest not personally. 
Also, IAS put an exhaustive "description" for the top level dictionary with 1951 characters (or 295 words). I think it should be more concise and maybe limiting it to 200 characters (or such) to get the message across that this is not where you document your products.

**Comment by jroulet** [comment]
I agree with everything, except perhaps we should allow empty event descriptions if there is nothing anomalous about the event? And use this field to e.g. warn about any unusual data quality considerations, etc?

**Comment by DrKentB** [comment]
I think the KEY for description should be in the JSON file, even if the VALUE is empty or "null".

**Comment by jroulet** [comment]
Ah, yes, then we are on the same page. The IAS json does have a "description" key for each event, albeit it appears later, below "pe_sets".
(The reason is python dataclasses do not let you put fields with default values (description=None)  ahead of fields without a default.)

**Comment by DrKentB** [comment]
My two cents on this is that a description other than None would be extremely valuable, possibly to the point of not supporting None.

**Comment by jkanner** [comment]
Address in branch `schema`

https://github.com/gwosc-tutorial/gwosc-catalog/commit/464d3de6e4e0edfc3bf754228289fcf99f4e84dd

**Comment by martinberoiz** [comment]
completed
