### ISSUE TITLE
Replace hyphens with underscores

### ISSUE THREAD

**Issue by martinberoiz** [gwosc-tutorial/gwosc-catalog#3]
Change hyphens to underscores, e.g. `data-url` -> `data_url` so we can use these directly as python keywords.

**Comment by jroulet** [comment]
We should also change to underscores in the `core.py` code.

**Comment by martinberoiz** [comment]
I agree, but I didn't do it because I'm kinda waiting on incorporating `schema.py` into the repo. Then we'll have to pretty much rewrite the validation code.
