### ISSUE TITLE
`is_default` attribute

### ISSUE THREAD

**Issue by jroulet** [gwosc-tutorial/gwosc-catalog#33]
In the schema, need to add a “is_default” attribute to the PE_Sets and (maybe) Search_sets (this needs to be a boolean)

**Comment by martinberoiz** [comment]
I think individual parameters could have a is_preferred label to the value that is preferred among the many in the PE sets.

**Comment by jroulet** [comment]
The way I implemented it, a whole `ParameterSet` is preferred or not. Is this not what we want?

If we make this for individual parameters, we could in principle display say the masses from one PE and the spins from a different PE. I think that would be confusing, is there any situation in which it would be desirable?

**Comment by martinberoiz** [comment]
Maybe I jumped the gun here, but I was thinking of a situation where a **PE** search has a far or snr parameter, and you mark it as preferred, but you want the corresponding value from a **search** peset instead. Or to have far from one search peset and snr from another. I see that this can be confusing though, and more work for the uploader which is not good. I also don't know if this is a realistic situation.

For intrinsic parameter estimations of the merger, I don't think mixing PE from different sets is a good idea.

If you think this is not a common situation or a bad idea, I'll fold.
