### ISSUE TITLE
Change best, lower and upper keys

### ISSUE THREAD

**Issue by martinberoiz** [gwosc-tutorial/gwosc-catalog#5]
`best`, `lower`, `upper` are ambiguous. We should we enforce that they are always median and 90% interval.

Rename them to `median`, `percentile_05`, and `percentile_95`.

**Comment by jkanner** [comment]
Rename to `upper_95` and `lower_05`.  Need to be clear that we store the difference from the median (e.g. the error bar), not the value of the upper/lower limit.

**Comment by martinberoiz** [comment]
I propose we change `upper_limit` to `is_upper_bound` and same for lower. I think this way it's more clear that it's a boolean and not the value.

**Comment by jkanner** [comment]
Addressed in the branch `schema`
