### ISSUE TITLE
Suggest relaxing unit requirements

### ISSUE THREAD

**Issue by dethodav** [gwosc-tutorial/gwosc-catalog#73]
I suggest that the specific unit requirements should be dropped for all fields in favor of requiring that provided units be compatible with `astropy.units`. 

In the schema documentation, there is the phrase 
> Acceptable values for solar mass abbreviation are the ones accepted by [astropy units](https://docs.astropy.org/en/stable/units/ref_api.html#module-astropy.units.astrophys) module: [solMass, M_sun, Msun].

This implies that the `astropy.units` module will be used when reading the provided catalog `JSON` file. Since this module also provides very straightforward tools to convert units, it seems that it is not necessary to require any specific units for parameters. Instead, I suggest that the schema note what unit parameters will be displayed on the GWOSC website, and require that the unit in the catalog JSON file be convertible to that unit with `astropy.units`. The [find_equivalent_units()](https://docs.astropy.org/en/stable/api/astropy.units.UnitBase.html#astropy.units.UnitBase.find_equivalent_units) method can be used to list all of the existing predefined units of a given type for each parameter.

For example, rather than requiring that masses be provided in units of `astropy.units.solMass`, users should be allowed to use any unit that is listed in `astropy.units.solMass.find_equivalent_units()`.

**Comment by DrKentB** [comment]
Hi Derek,
I am now in agreement with this suggestion. I need to code it up, but have tested out how this would work using the examples you provided.
